version: '3.3'

services:

    leantime:
        image: leantime/leantime:latest
        container_name: leantime
        ports:
            - "3306:3306"
        environment:
            - LEAN_DB_HOST=mysql
            - LEAN_DB_USER=ROOT
            - LEAN_DB_PASSWORD=root
            - LEAN_DB_DATABASE=leantime
           
    mysql:
        image: mysql
        container_name: mysql_leantime
        expose:
            - "3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root   
            - MYSQL_DATABASE=leantime
            - MYSQL_USER=ROOT
            - MYSQL_PASSWORD=root

          
